/*
 * Copyright 2026 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */

/**
 * Utilities for query parameter handling.
 *
 * Parameters are declared in src/assets/query-parameters.json (generated by
 * scripts/extract-query-parameters.js and reviewed by a human). Templates use
 * {{placeholder}} syntax for unambiguous value injection.
 */

/**
 * Validate that a string is a real calendar date in YYYY-MM-DD format.
 * Checks both the shape and that the date actually exists — rejecting
 * impossible dates like 2024-13-01 (month 13), 2024-02-30 (Feb 30),
 * or malformed values like 2024-115-15.
 * @param {string} str
 * @returns {boolean}
 */
export function isValidDate(str) {
  if (typeof str !== 'string') return false;
  const match = str.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(Date.UTC(year, month - 1, day));
  return (
    date.getUTCFullYear() === year &&
    date.getUTCMonth() === month - 1 &&
    date.getUTCDate() === day
  );
}

/**
 * Fill a query template by replacing {{placeholder}} tokens with values.
 *
 * For each parameter, replaces {{placeholder}} with a properly formatted
 * typed literal. For date parameters: "value"^^xsd:date.
 * If a value is invalid or missing, the default is used instead.
 *
 * @param {string} template - The query template with {{placeholder}} tokens.
 * @param {Array<{placeholder: string, type: string, default: string}>} parameters - Declared parameters.
 * @param {Array<string>} values - User-provided values (same order as parameters).
 * @returns {string} The filled query ready to execute.
 */
export function fillTemplate(template, parameters, values) {
  let result = template;
  for (let i = 0; i < parameters.length; i++) {
    const param = parameters[i];
    const userValue = values[i];

    // Use the user value if valid, otherwise fall back to default
    let finalValue;
    if (param.type === 'date') {
      finalValue = (userValue && isValidDate(userValue)) ? userValue : param.default;
    } else {
      finalValue = userValue || param.default;
    }

    // Build the typed literal
    let literal;
    if (param.type === 'date') {
      literal = `"${finalValue}"^^xsd:date`;
    } else {
      literal = `"${finalValue}"`;
    }

    // Replace all occurrences of the placeholder
    result = result.replaceAll(`{{${param.placeholder}}}`, literal);
  }
  return result;
}
