/*
 * Copyright 2026 European Union
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by the European
 * Commission – subsequent versions of the EUPL (the "Licence"); You may not use this work except in
 * compliance with the Licence. You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the Licence
 * is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the Licence for the specific language governing permissions and limitations under
 * the Licence.
 */

/**
 * Utilities for query parameter handling.
 *
 * Parameters are declared in src/assets/query-parameters.json (generated by
 * scripts/extract-query-parameters.js and reviewed by a human). Templates use
 * {{placeholder}} syntax for unambiguous value injection.
 */

/**
 * Validate that a string is a real calendar date in YYYY-MM-DD format.
 * @param {string} str
 * @returns {boolean}
 */
export function isValidDate(str) {
  if (typeof str !== 'string') return false;
  const match = str.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(Date.UTC(year, month - 1, day));
  return (
    date.getUTCFullYear() === year &&
    date.getUTCMonth() === month - 1 &&
    date.getUTCDate() === day
  );
}

/**
 * Validate that a string is a valid month in YYYY-MM format (month 01-12).
 * @param {string} str
 * @returns {boolean}
 */
export function isValidMonth(str) {
  if (typeof str !== 'string') return false;
  const match = str.match(/^(\d{4})-(\d{2})$/);
  if (!match) return false;
  const month = Number(match[2]);
  return month >= 1 && month <= 12;
}

/**
 * Validate that a string is a valid 4-digit year.
 * @param {string} str
 * @returns {boolean}
 */
export function isValidYear(str) {
  if (typeof str !== 'string') return false;
  return /^\d{4}$/.test(str);
}

/**
 * Get the last day of a given month (handles leap years).
 * @param {number} year
 * @param {number} month - 1-indexed (1=Jan, 12=Dec)
 * @returns {number} The last day (28, 29, 30, or 31)
 */
export function lastDayOfMonth(year, month) {
  // Day 0 of the next month gives the last day of the current month
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

/**
 * Fill a query template by replacing {{placeholder}} tokens with values.
 *
 * Supported parameter types:
 *   - "date": user provides YYYY-MM-DD → outputs "YYYY-MM-DD"^^xsd:date
 *   - "month-start": user provides YYYY-MM → outputs "YYYY-MM-01"^^xsd:date
 *   - "month-end": user provides YYYY-MM → outputs "YYYY-MM-{lastDay}"^^xsd:date
 *   - "year-start": user provides YYYY → outputs "YYYY-01-01"^^xsd:date
 *   - "year-end": user provides YYYY → outputs "YYYY-12-31"^^xsd:date
 *   - "text": user provides a string → outputs "value"
 *
 * If a value is invalid or missing, the default is used instead.
 *
 * @param {string} template - The query template with {{placeholder}} tokens.
 * @param {Array<{placeholder: string, type: string, default: string}>} parameters - Declared parameters.
 * @param {Array<string>} values - User-provided values (same order as parameters).
 * @returns {string} The filled query ready to execute.
 */
export function fillTemplate(template, parameters, values) {
  let result = template;
  for (let i = 0; i < parameters.length; i++) {
    const param = parameters[i];
    const userValue = values[i];

    let literal;
    switch (param.type) {
      case 'date': {
        const val = (userValue && isValidDate(userValue)) ? userValue : param.default;
        literal = `"${val}"^^xsd:date`;
        break;
      }
      case 'month-start': {
        const val = (userValue && isValidMonth(userValue)) ? userValue : param.default;
        literal = `"${val}-01"^^xsd:date`;
        break;
      }
      case 'month-end': {
        const val = (userValue && isValidMonth(userValue)) ? userValue : param.default;
        const [y, m] = val.split('-').map(Number);
        const last = String(lastDayOfMonth(y, m)).padStart(2, '0');
        literal = `"${val}-${last}"^^xsd:date`;
        break;
      }
      case 'year-start': {
        const val = (userValue && isValidYear(userValue)) ? userValue : param.default;
        literal = `"${val}-01-01"^^xsd:date`;
        break;
      }
      case 'year-end': {
        const val = (userValue && isValidYear(userValue)) ? userValue : param.default;
        literal = `"${val}-12-31"^^xsd:date`;
        break;
      }
      case 'date-raw': {
        // Outputs just the bare date string (no quotes, no type suffix).
        // The template itself contains the surrounding formatting.
        const val = (userValue && isValidDate(userValue)) ? userValue : param.default;
        literal = val;
        break;
      }
      default: {
        const val = (userValue && userValue.trim()) ? userValue : param.default;
        literal = `"${val}"`;
        break;
      }
    }

    result = result.replaceAll(`{{${param.placeholder}}}`, literal);
  }
  return result;
}
